sudo: required
services:
  - docker
before_install:
  - docker build -t sathyabodh/client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true sathyabodh/client-test npm test

after_success:
  - docker build -t sathyabodh/multi-client -f ./client/Dockerfile ./client
  - docker build -t sathyabodh/multi-server -f ./server/Dockerfile ./server
  - dokcer build -t sathyabodh/multi-nginx -f ./nginx/Dockerfile ./nginx
  - dokcer build -t sathyabodh/multi-worker -f ./worker/Dockerfile ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sathyabodh/multi-client
  - docker push sathyabodh/multi-server
  - docker push sathyabodh/multi-nginx
  - docker push sathyabodh/multi-worker
